config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews
  resources :users
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :restaurants, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
      @restaurant = Restaurant.create(restaurant_params)
        if @restaurant.valid?
            redirect_to restaurants_path
        else
            render "new"
        end
    end
    
    def edit
      @restaurant = Restaurant.find(params[:id])
    end

    def update
        @restaurant = Restaurant.find(params[:id])
        @restaurant.update(restaurant_params)
        @restaurant.save
        redirect_to @restaurant 
    end


    def destroy
      @restaurant = Restaurant.find(params[:id])
      @restaurant.destroy
        redirect_to restaurants_path
    end


    private

    def restaurant_params
        params.require(:restaurant).permit(:name,:cuisine,:location)
    end
end
    

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

     def create
        @user - User.create(user_params)
        if @user.valid?
            redirect_to users_path
        else
            render new_user_path
    end

    def edit
        @user = User.find(params[:id])
    end

     def update
        @user = User.find(params[:id])
        @user.update
    
    end
    
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :cuisine %>
<%= f.text_field :cuisine %>
<br>
<br>
<%= f.label :location %>
<%= f.text_field :location %>
<br>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <center>
<h1><b>Foodster</b></h1> 
<h3> Here to satisfy your hunger needs. </h3>
<br>   
<h2><em>Featured Restaurants</em></h2>
</head>

<body>
    <% @restaurants.each do |restaurant| %>
   <h3><li><%= link_to "#{restaurant.name}",restaurant %></li></h3> 
    <% end %>
<br> 
</body>


<%= button_to "Add a new restaurant", new_restaurant_path, method: :get %>
</center>


</html>

app/views/restaurants/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <center>
        <h1><b>Foodster</b></h1>
        <h3> Here to satisfy your hunger needs. </h3>
        <br>
        <h2><em>Let's Add a New Restaurant</em></h2>
</head>

<%= render "form" %>

app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html>

<head>
    <center>
        <h1>Foodster</h1>
        <h3> Here to satisfy your hunger needs. </h3>
</head>
<h2>
    <p><u><%= "#{@restaurant.name}"%></u></p>
</h2>
<h4>Cuisine: <%= "#{@restaurant.cuisine}"%></h4>
<h3>Location: <%= "#{@restaurant.location}"%></h4>

<h3><%="#{@restaurant.name}"%>'s Reviews</h3>
<li>
    
</li>


</center>
</html>

app/views/reviews/index.html.erb
<!DOCTYPE html>
<html>
    <head>


    </head>

    <body>



        
    </body>




</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
      <center>
          <h1><b>Foodster</b></h1> 
          <h3> Here to satisfy your hunger needs. </h3>
          <br>
          <h2><em>Featured Users</em></h2> 
</head>
    <body>
        <% @users.each do |user| %>
    <h3>
        <li><%= link_to "#{user.name}", user %></li></h3>
    <% end %>
    

</body>

</center>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <center>
        <h1><b>Foodster</b></h1>
        <h3> Here to satisfy your hunger needs. </h3>
        <br>
        <h2>Welcome <%= "#{@user.name}" %>!</h2>
</head>
<h3><%= "#{@user.name}"%>'s Reviews</h3>
 
    <li><%= link_to "#{@user.reviews.name}",review_path%></li> 

</center>
</html>